/**
 * Rental agreement PDF generator.
 *
 * Auto-fills a rental agreement from tenancy data. The clauses are a
 * clearly-labeled TEMPLATE — the owner should have it reviewed before use.
 * Signature blocks are left blank for wet or e-signature (no fake e-sign).
 */
import { jsPDF } from "jspdf"
import { supabase } from "@/lib/supabase"

export interface AgreementPdfData {
  ownerName: string
  tenantName: string
  propertyName: string
  propertyAddress: string
  flatNumber: string
  floorLabel: string
  monthlyRent: number
  deposit: number
  maintenance: number
  startDate: string
  endDate: string
  agreementDate: string
}

const MARGIN = 18
const W = 210
const INDIGO: [number, number, number] = [37, 64, 153]

function para(doc: jsPDF, text: string, y: number): number {
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(30, 30, 30)
  const lines = doc.splitTextToSize(text, W - MARGIN * 2)
  for (const line of lines) {
    if (y > 275) {
      doc.addPage()
      y = MARGIN
    }
    doc.text(line, MARGIN, y)
    y += 5.5
  }
  return y + 3
}

function heading(doc: jsPDF, text: string, y: number): number {
  if (y > 270) {
    doc.addPage()
    y = MARGIN
  }
  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  doc.setTextColor(...INDIGO)
  doc.text(text, MARGIN, y)
  return y + 8
}

/** Build the agreement PDF. Pure — no I/O. */
export function generateAgreementPdf(d: AgreementPdfData): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  let y = MARGIN

  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.setTextColor(...INDIGO)
  doc.text("RENTAL AGREEMENT", W / 2, y + 6, { align: "center" })
  y += 12
  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(140, 140, 140)
  doc.text("Generated by RentTrack — template clauses, review before signing", W / 2, y, { align: "center" })
  y += 10

  y = heading(doc, "Parties", y)
  y = para(
    doc,
    `This agreement is made on ${d.agreementDate} between ${d.ownerName} (hereinafter "the Owner") ` +
      `and ${d.tenantName} (hereinafter "the Tenant") for the rental of the premises described below.`,
    y
  )

  y = heading(doc, "Premises", y)
  y = para(
    doc,
    `${d.propertyName}, ${d.propertyAddress}. Flat/Room No. ${d.flatNumber}` +
      (d.floorLabel ? `, ${d.floorLabel}` : "") +
      `. The Tenant shall use the premises for residential purposes only.`,
    y
  )

  y = heading(doc, "Term", y)
  y = para(
    doc,
    `The tenancy begins on ${d.startDate} and ends on ${d.endDate}, unless terminated earlier ` +
      `in accordance with this agreement.`,
    y
  )

  y = heading(doc, "Rent and Deposit", y)
  y = para(
    doc,
    `Monthly rent: Rs. ${d.monthlyRent.toFixed(2)}, payable on or before the 5th of each month. ` +
      (d.maintenance > 0
        ? `Monthly maintenance: Rs. ${d.maintenance.toFixed(2)}. `
        : "") +
      `Security deposit: Rs. ${d.deposit.toFixed(2)}, refundable at the end of the tenancy after ` +
      `adjusting for unpaid dues and damages beyond normal wear. The deposit is not adjustable against monthly rent.`,
    y
  )

  y = heading(doc, "Standard Clauses (template)", y)
  const clauses = [
    "1. The Tenant shall keep the premises clean and in good condition, and shall not make structural alterations without the Owner's written consent.",
    "2. The Tenant shall pay electricity, water/bore, and other utility charges as billed, in addition to the monthly rent, unless agreed otherwise.",
    "3. Either party may terminate this agreement with one month's written notice.",
    "4. On vacating, the Tenant shall hand over vacant possession in the same condition as received, subject to normal wear and tear.",
    "5. Any disputes shall first be attempted to be resolved amicably between the parties.",
  ]
  for (const c of clauses) y = para(doc, c, y)

  y = heading(doc, "Signatures", y)
  y = para(doc, "Signed in agreement to the above terms.", y)
  y += 6
  const sig = (label: string, x: number) => {
    doc.setDrawColor(120, 120, 120)
    doc.line(x, y + 18, x + 60, y + 18)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    doc.setTextColor(110, 110, 110)
    doc.text(label, x, y + 24)
  }
  sig("Owner", MARGIN)
  sig("Tenant", MARGIN + 75)
  if (y + 40 > 275) {
    doc.addPage()
    y = MARGIN
  } else {
    y += 40
  }
  sig("Witness 1", MARGIN)
  sig("Witness 2", MARGIN + 75)

  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Page ${i} of ${pages}`, W - MARGIN - 18, 290)
  }
  return doc
}

/** Save a generated agreement PDF to the private rental-agreements bucket. */
export async function uploadAgreementPdf(
  doc: jsPDF,
  propertyId: string,
  agreementId: string
): Promise<string> {
  const blob = doc.output("blob")
  const path = `${propertyId}/${agreementId}-generated.pdf`
  const { error } = await supabase.storage
    .from("rental-agreements")
    .upload(path, blob, { contentType: "application/pdf", upsert: true })
  if (error) throw new Error(error.message)
  return path
}
